---
- name: Check if already attached
  stat:
    path: "/etc/systemd/system/ibm-host-attach.service"
  register: stat_result
  ignore_unreachable: true

- name: Attach host to Satellite
  block:
    - name: Enable subscriptions
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      with_items:
        - rhel-server-rhscl-7-rpms
        - rhel-server-rhscl-7-rpms
        - rhel-server-rhscl-7-rpms
        - rhel-7-server-supplementary-rpms
        - rhel-7-server-extras-rpms

    - name: copy script
      copy:
        src: "{{hostvars['localhost']['sat_attach_script']}}"
        dest: "/root/attach_host.sh"
        mode: '0755'
        
    - name: run script
      shell: |
        /root/attach_host.sh
  when: stat_result.stat is defined and stat_result.stat.exists == False