---
- name: get volume id
  command: ibmcloud is vols --zone {{ hostvars[roks_host]['sat_host']['infrastructure']['zone'] }} --resource-group-name {{ all_config.resource_group[0].name }} --output json -q
  register: output

- name: parse volume id
  set_fact:
    _volume_id: "{{output.stdout | from_json | json_query(query) | first}}"
  vars:
    query: "[?name=='{{hostvars[roks_host]['sat_host']['name']}}-data2'].id"

- name: parse status
  set_fact:
    _status: "{{output.stdout | from_json | json_query(query) | first}}"
  vars:
    query: "[?name=='{{hostvars[roks_host]['sat_host']['name']}}-data2'].attachment_state"

- debug:
    var: _status

- name: attach volume
  command: ibmcloud is in-vola odf-vol {{ hostvars[roks_host]['sat_host']['name'] }} {{ _volume_id }}
  when: _status == "unattached"
