---
- name: get status
  command: ibmcloud oc worker-pool get --cluster {{cluster_name}} --worker-pool default --output json -q
  register: output

- name: assign zone
  command: ibmcloud oc zone add satellite --cluster {{cluster_name}} --zone {{zone}} --worker-pool default
  when: output.stdout | from_json | json_query(query) | length == 0
  vars:
    query: "zones[?id == '{{zone}}']"