---
- name: get status
  command: ibmcloud sat host ls --location {{all_config.satellite[0].name}} --output json -q
  register: output

- name: get host id
  set_fact:
    _host_id: "{{output.stdout | from_json | json_query(query) | first}}"
  vars:
    query: "[?name=='{{hostvars[roks_host]['sat_host']['name']}}'].id"

- name: assign
  command: ibmcloud sat host assign --location {{all_config.satellite[0].name}} --cluster {{cluster_name}} --host {{_host_id}} --zone {{zone}}
  when: output.stdout | from_json | json_query(query) | first == ""
  vars:
    query: "[?name=='{{ hostvars[roks_host]['sat_host']['name'] }}'].assignment.clusterID"