apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: ibm-mas-visualinspection-clusterrole
rules:
- apiGroups:
  - 'security.openshift.io'
  resources:
  - 'securitycontextconstraints'
  resourceNames:
  - 'ibm-mas-visualinspection-scc'
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list
