---

#- name: Install required packages for Ansible
#  raw: yum install -y python38

- name: Enable TCP forwarding on bastion node
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowTcpForwarding no"
    line: "AllowTcpForwarding yes"
    state: present

- name: Restart sshd service
  service:
    name: sshd
    state: restarted