---
- name: 30 - Provision infrastructure
  hosts: localhost
  connection: local
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""
    ansible_callback_diy_playbook_on_include_msg: ""

  tasks:
    - name: Provision infrastructure using Terraform
      include_role:
        name: provision-terraform
      when: cloud_platform == 'ibm-cloud'

