---

- name: 40 - Configure infrastructure
  hosts: localhost
  connection: local
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""
    ansible_callback_diy_playbook_on_include_msg: ""

  tasks:
  - name: Assemble Satellite Servers group
    include_role:
      name: sat-host
    when: cloud_platform == 'ibm-cloud'

- name: 40 - Configure infrastructure - Bastion server
  hosts: vpc_bastion_server
  become: True
  gather_facts: True

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""

  tasks:
  - name: Configure bastion server
    include_role: 
      name: sat-host-ibmcloud-vpc-bastion
    vars:
      allowed_ips: "{{ hostvars['localhost']['all_config'] | json_query('subnet[*].ipv4_cidr_block') | join(',') }}"
      client_conf_path: '{{status_dir}}/downloads/'

- name: 40 - Configure infrastructure - Satellite servers - master
  hosts: sat_hosts_master
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""

  tasks:
  - name: Configure Satellite servers - masters
    include_role: 
      name: sat-host-ibmcloud-vpc-install
    
- name: 40 - Configure infrastructure - Satellite servers - worker
  hosts: sat_hosts_ocp
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""

  tasks:
  - name: Configure Satellite servers - workers
    include_role: 
      name: sat-host-ibmcloud-vpc-install

- name: 40 - Configure infrastructure - Satellite
  hosts: localhost
  connection: local
  become: True
  gather_facts: False

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""

  tasks:
  - name: Configure Satellite
    include_role: 
      name: satellite-configure
    vars:
      sat_hosts_cp: "{{groups['sat_hosts_master']}}"
      sat_hosts_ocp: "{{groups['sat_hosts_ocp']}}"

- name: 40 - Configure infrastructure - Loadbalancer
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    sat_hosts_ocp: "{{groups['sat_hosts_ocp']}}"

  tasks:
  - name: Configure loadbalancer
    ansible.builtin.include_role:
      name: satellite-configure-lb
    when: all_config['loadbalancer'] is defined
