---
- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined

- include_tasks: ibmcloud-download-cli.yml
  when: cloud_platform == 'ibm-cloud'

- name: Download OpenShift client
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: "{{ all_config.satellite[0].services.openshift.version }}"
    _download_dir: "{{ status_dir }}"
  when: all_config['satellite'][0]['services'] is defined and
        all_config['satellite'][0]['services']['openshift'] is defined
