---
- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined

- include_tasks: ibmcloud-download-cli.yml
  when: cloud_platform == 'ibm-cloud'

- name: Download OpenShift client
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: '4.10'
    _download_dir: "{{ status_dir }}"
